### ISSUE TITLE
Build failed, during cargo run

### ISSUE THREAD

**Issue by KshitijKarthick** [nukep/llamadb#21]
![screenshot from 2015-04-20 07 47 52](https://cloud.githubusercontent.com/assets/6723677/7222730/b383d77e-e731-11e4-9043-f4d9754630c2.png)
![screenshot from 2015-04-20 07 48 43](https://cloud.githubusercontent.com/assets/6723677/7222731/b3850234-e731-11e4-9ac5-5a463fb7273b.png)

thread 'rustc' panicked at 'Trying to convert unsized value to lval', /build/rust/src/rustc-1.0.0-alpha.2/src/librustc_trans/trans/datum.rs:495

**Comment by nukep** [comment]
Could you verify which version of Rust you have installed by entering `rustc --version`?
It should build successfully with the latest Rust nightly (not the beta).

EDIT: It says you're running Rust alpha, which is too old.

**Comment by KshitijKarthick** [comment]
rustc --version
rustc 1.0.0-dev (built 2015-02-23)
This is the version available in the AUR, for package name rust
